spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@127.0.0.1:27018/admin
      database: admin
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaUser: "kafka-topic-name"
    kafkaBooking: "kafka-booking"
    kafkaUserGroupId: "kafka-user-group"