spring:
  data:
    mongodb:
      uri: mongodb://mongo:mongo@127.0.0.1:27018/admin
      database: admin

app:
  jwt:
    secret: "SomeSecretKeyoidhujh9jkoi9ydhuj534nh89jjnhs7xvjmhziklogjmmskmrpojksgns8ejHUYhfnnbythbfhjz7lUHNN89f79gin58ujmgnbn"
    tokenExpiration: 100m
    refreshTokenExpiration: 10000m